# This action checks for broken links
name: Check Links

on:
  push:
  pull_request:
  schedule:
    - cron: "00 00 * * *"

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Restore lychee cache
        uses: actions/cache@v5
        with:
          path: .lycheecache
          key: cache-lychee-${{ github.sha }}
          restore-keys: cache-lychee-

      - name: 🔗 Check Links
        uses: lycheeverse/lychee-action@v2
        with:
          jobSummary: true
          args: --base-url https://pestphp.test --cache --max-cache-age 1d --config .github/workflows/lychee.toml './**/*.md'
